In [103]:
import pandas as pd
import numpy as np
from selenium import webdriver
from bs4 import BeautifulSoup
from tqdm import tqdm_notebook
from urllib.request import urlopen

import time
import re

In [106]:
driver = webdriver.Chrome('chromedriver.exe')

url = 'https://www.hyundaicard.com/cpu/cs/CPUCS0701_01.hc'
driver.get(url)

for i in range(3):
    driver.find_element_by_xpath('//span[@id="moreNum"]').click()

In [107]:
html = driver.page_source
soup = BeautifulSoup(html, 'html.parser')
title = soup.select('p.location')
Title = []

for i in range(len(title)) :
    tmp_t = title[i].text.strip()
    
    Title.append(tmp_t)

In [108]:
df1_t = pd.DataFrame(Title)

In [109]:
df1_t

                                                    0
0   지역 : PLCC이마트강남지점 | 연락처 : 02-3490-1613 | 주소 : 서...
1   지역 : PLCC이마트강동지점 | 연락처 : 02-3490-1661 | 주소 : 서...
2   지역 : PLCC이마트강북지점 | 연락처 : 02-950-9967 | 주소 : 서울...
3   지역 : PLCC이마트강서지점 | 연락처 : 02-818-4270 | 주소 : 서울...
4   지역 : PLCC이마트광주지점 | 연락처 : 062-239-9104 | 주소 : 광...
5   지역 : PLCC이마트대구지점 | 연락처 : 053-757-3400 | 주소 : 대...
6   지역 : PLCC이마트대전지점 | 연락처 : 042-828-4352 | 주소 : 대...
7   지역 : PLCC이마트부산지점 | 연락처 : 051-810-9800 | 주소 : 부...
8   지역 : PLCC이마트수원지점 | 연락처 : 031-548-5880 | 주소 : 경...
9   지역 : PLCC이마트인천지점 | 연락처 : 032-717-3595 | 주소 : 인...
10  지역 : 강남 | 연락처 : 02-2023-9500 | 주소 : 서울시 서초구 강남...
11  지역 : 강북 | 연락처 : 02-2092-3500 | 주소 : 서울시 노원구 노해...
12  지역 : 광주 | 연락처 : 062-239-9140 | 주소 : 광주시 서구 시청로...
13  지역 : 남대구 | 연락처 : 053-251-6780 | 주소 : 대구광역시 중구 ...
14  지역 : 노원 | 연락처 : 02-2092-4203 | 주소 : 서울시 노원구 노해...
15  지역 : 대구 | 연락처 : 053-430-2800 | 주소 : 대구시 중구 중앙대...
16  지역 : 대전 | 연락처 : 042-828-4330 | 주소 : 대전광역시 서구 둔...
17  지역 : 동인천 | 연락처 : 032-717-3561 | 주소 : 인천시 부평구 부...
18  지역 : 둔산 | 연락처 : 042-828-4340 | 주소 : 대전광역시 서구 둔...
19  지역 : 마포 | 연락처 : 02-2029-0406 | 주소 : 서울시 영등포구 국...
20  지역 : 부산 | 연락처 : 051-801-5500 | 주소 : 부산시 부산진구 서...
21  지역 : 부평 | 연락처 : 032-717-3552 | 주소 : 인천시 부평구 부평...
22  지역 : 북대구 | 연락처 : 053-251-6700 | 주소 : 대구시 중구 중앙...
23  지역 : 상무 | 연락처 : 062-380-5900 | 주소 : 광주시 서구 시청로...
24  지역 : 서면 | 연락처 : 051-607-8307 | 주소 : 부산시 부산진구 서...
25  지역 : 서부카드 | 연락처 : 02-2069-8745 | 주소 : 서울시 영등포구...
26  지역 : 서초 | 연락처 : 02-526-7100 | 주소 : 서울시 서초구 강남대...
27  지역 : 선릉 | 연락처 : 02-2240-4200 | 주소 : 서울시 서초구 강남...
28  지역 : 송파 | 연락처 : 02-526-7104 | 주소 : 서울시 서초구 강남대...
29  지역 : 수원 | 연락처 : 031-548-5800 | 주소 : 경기도 수원시 팔달...
30  지역 : 안산 | 연락처 : 031-412-0900 | 주소 : 경기도 안산시 단원...
31  지역 : 양천 | 연락처 : 02-860-5001 | 주소 : 서울시 영등포구 국회...
32  지역 : 여의도 | 연락처 : 02-818-4200 | 주소 : 서울시 영등포구 영...
33  지역 : 영등포 | 연락처 : 02-705-4000 | 주소 : 서울시 영등포구 국...
34  지역 : 인천 | 연락처 : 032-717-3581 | 주소 : 인천시 부평구 부평...
35  지역 : 전주 | 연락처 : 063-280-1700 | 주소 : 전북 전주시 완산구...
36  지역 : 창원 | 연락처 : 055-239-6920 | 주소 : 경남 창원시 성산구...
37  지역 : 천안 | 연락처 : 041-590-5900 | 주소 : 충남 천안시 서북구...
38  지역 : 현대기아본사 | 연락처 : 02-574-4224 | 주소 : 서울시 서초구...

In [117]:
df1=pd.DataFrame(df1_t[0].str.split(':').str[3])

In [133]:
raw_data={'1':df1[0].str.split(' ').str[1],
          '2':df1[0].str.split(' ').str[2],
          '3':df1[0].str.split(' ').str[3]}

data = pd.DataFrame(raw_data)
data

        1     2     3
0   서울특별시   서초구  강남대로
1   서울특별시   서초구  강남대로
2   서울특별시   노원구   노해로
3   서울특별시  영등포구  국회대로
4   광주광역시    서구   시청로
5   대구광역시    중구  중앙대로
6   대전광역시    서구   둔산로
7   부산광역시  부산진구   서전로
8     경기도   수원시   팔달구
9   인천광역시   부평구  부평대로
10    서울시   서초구  강남대로
11    서울시   노원구   노해로
12    광주시    서구   시청로
13  대구광역시    중구  중앙대로
14    서울시   노원구   노해로
15    대구시    중구  중앙대로
16  대전광역시    서구   둔산로
17    인천시   부평구  부평대로
18  대전광역시    서구   둔산로
19    서울시  영등포구  국회대로
20    부산시  부산진구  서전로8
21    인천시   부평구  부평대로
22    대구시    중구  중앙대로
23    광주시    서구   시청로
24    부산시  부산진구  서전로8
25    서울시  영등포구  국회대로
26    서울시   서초구  강남대로
27    서울시   서초구  강남대로
28    서울시   서초구  강남대로
29    경기도   수원시   팔달구
30    경기도   안산시   단원구
31    서울시  영등포구  국회대로
32    서울시  영등포구  영등포로
33    서울시  영등포구  국회대로
34    인천시   부평구  부평대로
35     전북   전주시   완산구
36     경남   창원시   성산구
37     충남   천안시   서북구
38    서울시   서초구   헌릉로

In [135]:
data.to_csv("현대카드.csv", index=False, encoding='CP949')